[terminal.shell]
program = "/usr/bin/zsh"
args = [ "--login", ]

[env]
TERM = "xterm-256color"

[window]
#dimensions = { columns = 0, lines = 0 }
padding = { x = 2, y = 2 }
decorations = "None"
opacity = 1.0
blur = true

[scrolling]
history = 65535

[font]
normal = { family = "MesloLGM Nerd Font", style = "Regular" }
bold = { family = "MesloLGM Nerd Font", style = "Bold" }
italic = { family = "MesloLGM Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGM Nerd Font", style = "Bold Italic" }
#size = 11.25
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#C0C5CE"
command = { program = "notify-send", args = ["alacritty", "bell",] }

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Beam"
blinking = "Always"

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "Paste", action = "Paste" },
  { key = "Copy", action = "Copy" },
  { key = "Insert", mods = "Shift", action = "PasteSelection" },
  { key = "F", mods = "Control|Shift", action = "SearchForward", mode = "~Search" },
  { key = "B", mods = "Control|Shift", action = "SearchBackward", mode = "~Search" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
]

[general]
import = [
 "~/.config/alacritty/catpuccin-mocha.toml",
	# "~/.config/alacritty/keybindings.toml",
]

[terminal]

